config/routes.rb
Rails.application.routes.draw do

  #post "likes/:tweet_id/create" => "likes#create"
  #post "likes/:tweet_id/destroy" => "likes#destroy"

  resources :users, :except => :new
  get "signup" => "users#new"
  post "login" => "users#login"
  post "logout" => "users#logout"
  get "login" => "users#login_form"
  get "users/:id/likes" => "users#likes"

  resources :tweets do
    resource :likes, only: [:create, :destroy]
  end

  root :to => "home#top"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  
	validates :user_id, {presence: true}
  	validates :tweet_id, {presence: true}
end

app/models/tweet.rb
class Tweet < ApplicationRecord
	validates :body,{presence: true, length: {maximum: 140}}
	validates :user_id, {presence: true}

	def user
    	return User.find_by(id: self.user_id)
  	end
end

app/models/user.rb
class User < ApplicationRecord

	has_secure_password
	
	has_many :likes

	validates :name, {presence: true}
	validates :email, {presence: true,uniqueness: true}

	def tweets
    return Tweet.where(user_id: self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	# current_userの定義
	before_action :set_current_user

	def set_current_user
      @current_user = User.find_by(id: session[:user_id])
    end

    def authenticate_user
    	if @current_user == nil
    		flash[:notice] = "ログインが必要です"
    		redirect_to ("/login")
    	end
    end

    def forbid_login_user
	    if @current_user
	    flash[:notice] = "すでにログインしています"
	    redirect_to("/tweets")
	    end
 	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	before_action :forbid_login_user
  def top
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :authenticate_user

  def create
  	@like = Like.new(
      user_id: @current_user.id,
      tweet_id: params[:tweet_id]
      )
    @like.save
    redirect_to ("/tweets/#{params[:tweet_id]}")
  end

  def destroy
  	@like = Like.find_by(
  		user_id: @current_user.id,
      tweet_id: params[:tweet_id]
  		)
  	@like.destroy
  	redirect_to ("/tweets/#{params[:tweet_id]}")
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action :authenticate_user
  before_action :ensure_correct_user,{only: [:edit, :update, :destroy]}

  def index
  	@tweets = Tweet.all.order(created_at: :desc)
  end

  def show
  	@tweet = Tweet.find_by(id: params[:id])
    @user = @tweet.user
  end

  def edit
  	@tweet = Tweet.find_by(id: params[:id])
  end

  def new
  	@tweet = Tweet.new
  end

  def create
  	@tweet = Tweet.new(
      body: params[:body],
      user_id: @current_user.id
      )
    if @tweet.save
    	flash[:notice] = "投稿しました"
  		redirect_to ("/tweets")
    else
    	render ("/tweets/new")
    end
  end

  def update
  	@tweet = Tweet.find_by(id: params[:id])
    @tweet.body = params[:body]
    if @tweet.save
    	flash[:notice] = "投稿を編集しました"
  		redirect_to ("/tweets")
  	else
  		render("tweets/edit")
  	end
  end

  def destroy
  	@tweet = Tweet.find_by(id: params[:id])
    @tweet.destroy
    flash[:notice] = "投稿を削除しました"
  	redirect_to ("/tweets")
  end

  def ensure_correct_user
    @tweet = Tweet.find_by(id: params[:id])
    if @tweet.user_id != @current_user.id
      flash[:notice] = "権限がありません"
      redirect_to("/posts/index")
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # ログインしていない時は入れない
  before_action :authenticate_user, {only: [:index, :show, :edit, :update]}
  # ログインしている時に入れなくなる
  before_action :forbid_login_user,{only: [:new, :create, :login_form, :login]}
  # urlを打っても入れなくする.
  before_action :ensure_correct_user,{only: [:edit, :update]}

  def index
  	@users = User.all
  end

  def show
  	@user = User.find_by(id: params[:id])
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find_by(id: params[:id])
    @user.name = params[:name]
    @user.email = params[:email]

    # 画像を更新する時は画像名をuser.idに変更してpublic/user_imeagesに保存する
    if params[:image]
      image = params[:image]
      @user.icon_id = "#{@user.id}.jpg"
      File.binwrite("public/user_images/#{@user.icon_id}",image.read)
    end

    if @user.save
      flash[:notice] = "ユーザー情報を編集しました"
      redirect_to ("/users/#{@user.id}")
    else
      render ("/users/edit")
    end
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(
      name: params[:name],
      email: params[:email],
      password: params[:password],
      icon_id: "no_image.jpg"
      )
  	if @user.save
      session[:user_id] = @user.id
  		flash[:notice] = "ユーザー登録が完了しました"
		redirect_to ("/users/#{@user.id}")
	 else
		render ("/users/new")
	 end
  end

  def login_form
  end

  def login
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
    end
    if @user
      session[:user_id] = @user.id
      flash[:notice] = "ログインしました"
      redirect_to ("/tweets")
    else
      @error_message = "メールアドレスまたはパスワードが間違っています"
      @email = params[:email]
      render ("users/login_form")
    end
  end

  def logout
    session[:user_id] = nil
    flash[:notice] = "ログアウトしました"
    redirect_to ("/login")
  end

  def likes
    @user = User.find_by(id: params[:id])
    @likes = Like.where(user_id: @user.id)
  end

  def ensure_correct_user
    if @current_user.id != params[:id].to_i
    flash[:notice] = "権限がありません"
    redirect_to("/tweets")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# ページごとの完全なタイトルを返します。
  def full_title(page_title = '')
    base_title = "Tweet"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/top.html.erb
<div class="main top-main">
  <div class="top-message">
    <h2>つぶやきで、世界はつながる</h2>
    <p>今の気持ちをつぶやいてみよう！</p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TweetApp</title>
    <%= csrf_meta_tags %>
    <%# <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/6f0d38cdd3.js" crossorigin="anonymous"></script>
  </head>

  <body>

    <header>
      <div class="header-logo">
        <% if @current_user %>
       <%= link_to("TweetApp","/") %>
       <% end %>
      </div>

      <ul class="header-menus">
        <% if @current_user %>
          <li>
            <%= link_to(@current_user.name, "/users/#{@current_user.id}") %>
          </li>
          <li>
          <%= link_to "投稿一覧", tweets_path %>
          </li>
          <li>
            <%= link_to("新規投稿", "/tweets/new") %>
          </li>
          <li>
            <%= link_to("ユーザー一覧", "/users") %>
          </li>
          <li>
              <%= link_to("ログアウト", "/logout", {method: :post}) %>
          </li>
        <% else %>
          <li>
            <%= link_to("新規登録", "/signup") %>
          </li>
          <li>
            <%= link_to("ログイン", "/login") %>
          </li>
        <% end %>
      </ul>
    </header>

    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/tweets/edit.html.erb
<div class="main tweets-new">
  <div class="container">
    <h1 class="form-heading">編集する</h1>
    <%= form_tag tweet_path(@tweet.id), method: :patch do %>
	    <div class="form">
	      <div class="form-body">
	      	<% @tweet.errors.full_messages.each do |message| %>
	          <div class="form-error">
	            <%= message %>
	          </div>
	        <% end %>
	        <textarea name="body"><%= @tweet.body %></textarea>
	        <input type="submit" value="保存">
	      </div>
	    </div>
    <% end %>
  </div>
</div>

app/views/tweets/index.html.erb
<div class="main tweets-index">
  <div class="container">
    <% @tweets.each do |tweet| %>
      <div class="tweets-index-item">
      	<div class="tweet-left">
          <img src="<%= "/user_images/#{tweet.user.icon_id}" %>">
        </div>
        <div class="tweet-right">
          <div class="tweet-user-name">
            <%= link_to(tweet.user.name, "/users/#{tweet.user.id}") %>
          </div>
        <%=link_to(tweet.body,"/tweets/#{tweet.id}") %>
      </div>
    </div>
  <% end %>
</div>

app/views/tweets/new.html.erb
<div class="main tweets-new">
  <div class="container">
    <h1 class="form-heading">投稿する</h1>
    <%= form_tag tweets_path do %>
      <div class="form">
        <div class="form-body">
        	<% @tweet.errors.full_messages.each do |message| %>
            <div class="form-error">
              <%= message %>
            </div>
          <% end %>
          <textarea name="body"><%= @tweet.body %></textarea>
          <input type="submit" value="投稿">
        </div>
      </div>
    <%end%>
  </div>
</div>

app/views/tweets/show.html.erb
<div class="main tweets-show">
  <div class="container">
    <div class="tweets-show-item">
      <div class="tweet-user-name">
        <img src="<%= "/user_images/#{@user.icon_id}" %>">
        <%= link_to(@user.name,"/users/#{@user.id}") %>
      </div>
      <p>
        <%= @tweet.body %>
      </p>
      <div class="tweet-time">
        <%= @tweet.created_at %>
      </div>

      <% if Like.find_by(user_id: @current_user.id, tweet_id: @tweet.id) %>
        <%= link_to tweet_likes_path(@tweet), method: :delete do %>
          <span class="fa fa-heart like-btn-unlike"></span>
        <% end %>

        <% else %>

        <%= link_to tweet_likes_path(@tweet), method: :post do %>
          <span class="fa fa-heart like-btn"></span>
        <% end %>
      <% end %>
        <%= @likes_count %>

      <% if @tweet.user_id == @current_user.id %>
      <div class="tweet-menus">
        <%= link_to("編集", "/tweets/#{@tweet.id}/edit") %>
        <%= link_to "削除", tweet_path(@tweet.id), method: :delete %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="main users-edit">
  <div class="container">
    <div class="form-heading">アカウント編集</div>
    <div class="form users-form">
      <div class="form-body">
        <% @user.errors.full_messages.each do |message| %>
          <div class="form-error">
            <%= message %>
          </div>
        <% end %>

        <!-- 画像を送信する時はform_tagにmultipart: trueを追加する -->
        <%= form_tag user_path(@user.id), multipart: true, method: :patch do %>
          <p>ユーザー名</p>
          <input name="name" value="<%= @user.name %>">
          <p>画像</p>
          <input name="image" type="file">
          <p>メールアドレス</p>
          <input name="email" value="<%= @user.email %>">
          <input type="submit" value="保存">
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="main users-index">
  <div class="container">
    <h1 class="users-heading">ユーザー一覧</h1>
    <% @users.each do |user| %>
      <div class="users-index-item">
        <div class="user-left">
        	<img src="<%= "/user_images/#{user.icon_id}" %>">
        </div>
        <div class="user-right">
          <%= link_to(user.name, "/users/#{user.id}") %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/likes.html.erb
<div class="main user-show">
  <div class="container">
    <div class="user">
      <img src="<%= "/user_images/#{@user.icon_id}" %>">
      <h2><%= @user.name %></h2>
      <p><%= @user.email %></p>
      <% if @user.id == @current_user.id %>
        <%= link_to("編集", "/users/#{@user.id}/edit") %>
      <% end %>
    </div>

    <ul class="user-tabs">
      <li><%= link_to("投稿", "/users/#{@user.id}") %></li>
      <li class="active"><%= link_to("いいね!", "/users/#{@user.id}/likes") %></li>
    </ul>

    <% @likes.each do |like| %>
      <% tweet = Tweet.find_by(id: like.tweet_id) %>
      <div class="tweets-index-item">
        <div class="tweet-left">
          <img src="<%= "/user_images/#{tweet.user.icon_id}" %>">
        </div>
        <div class="tweet-right">
          <div class="tweet-user-name">
            <%= link_to(tweet.user.name, "/users/#{tweet.user.id}") %>
          </div>
          <%= link_to(tweet.body, "/tweets/#{tweet.id}") %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/login_form.html.erb
<div class="main users-new">
  <div class="container">
    <div class="form-heading">ログイン</div>
    <div class="form users-form">
      <div class="form-body">
        <% if @error_message %>
          <div class="form-error">
            <%= @error_message %>
          </div>
        <% end %>
        <%= form_tag("/login") do %>
          <p>メールアドレス</p>
          <input name="email" value="<%= @email %>">
          <p>パスワード</p>
          <input type="password" name="password">
          <input type="submit" value="ログイン">
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="main users-new">
  <div class="container">
    <div class="form-heading">新規ユーザー登録</div>
    <div class="form users-form">
      <div class="form-body">
        <% @user.errors.full_messages.each do |message| %>
          <div class="form-error">
            <%= message %>
          </div>
        <% end %>
        <%= form_tag users_path do %>
          <p>ユーザー名</p>
          <input name="name" value="<%= @user.name %>">
          <p>メールアドレス</p>
          <input name="email" value="<%= @user.email %>">
          <p>パスワード</p>
          <input type="password" name="password">
          <input type="submit" value="新規登録">
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="main user-show">
  <div class="container">
    <div class="user">
    	<img src="<%= "/user_images/#{@user.icon_id}" %>">
      <h2><%= @user.name %></h2>
      <p><%= @user.email %></p>
      <% if @user.id == @current_user.id %>
        <%= link_to("編集", "/users/#{@user.id}/edit") %>
      <% end %>
    </div>

    <ul class="user-tabs">
      <li class="active"><%= link_to("投稿", "/users/#{@user.id}") %></li>
      <li><%= link_to("いいね!", "/users/#{@user.id}/likes") %></li>
    </ul>

    <% @user.tweets.each do |tweet| %>
      <div class="tweets-index-item">
        <div class="tweet-left">
          <img src="<%= "/user_images/#{tweet.user.icon_id}" %>">
        </div>
        <div class="tweet-right">
          <div class="tweet-user-name">
            <%= link_to(tweet.user.name, "/users/#{tweet.user.id}") %>
          </div>
          <%= link_to(tweet.body, "/tweets/#{tweet.id}") %>
        </div>
      </div>
    <% end %>
  </div>
</div>